apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.ports.otlpHttp }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
