{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prd-web-agent.fullname" . }}
  labels:
    {{- include "prd-web-agent.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
